[package]
name = "ebs"
version = "0.0.1"
authors = ["Michał Żaloudik <ponury.kostek@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "ebs"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
bytebuffer = "0.2.1"
